functions:
  users:
    handler: users.handler
    events:
      - s3:
          bucket: desafio-final
          event: s3:ObjectCreated:*
          rules:
            - prefix: entrada-dados/
            - suffix: .json
          existing: true
